// <auto-generated />
using Capstone_Donation_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Capstone_Donation_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200306163627_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Capstone_Donation_API.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("AddressID");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            AddressID = 1,
                            City = "oconomowoc",
                            State = "wi",
                            StreetName = "329 e pleasant st",
                            ZipCode = 53066
                        },
                        new
                        {
                            AddressID = 2,
                            City = "milwaukee",
                            State = "wi",
                            StreetName = "324 s second st",
                            ZipCode = 53204
                        },
                        new
                        {
                            AddressID = 3,
                            City = "milwaukee",
                            State = "wi",
                            StreetName = "2100 n kilian pl",
                            ZipCode = 53212
                        },
                        new
                        {
                            AddressID = 4,
                            City = "west allis",
                            State = "wi",
                            StreetName = "1427 s 75th st",
                            ZipCode = 53214
                        },
                        new
                        {
                            AddressID = 5,
                            City = "madison",
                            State = "wi",
                            StreetName = "1100 bowen ct",
                            ZipCode = 53715
                        },
                        new
                        {
                            AddressID = 6,
                            City = "naperville",
                            State = "il",
                            StreetName = "874 havenshire rd",
                            ZipCode = 60565
                        },
                        new
                        {
                            AddressID = 7,
                            City = "st paul",
                            State = "mn",
                            StreetName = "177 mcknight rd n",
                            ZipCode = 55119
                        },
                        new
                        {
                            AddressID = 8,
                            City = "waukesha",
                            State = "wi",
                            StreetName = "114 douglass ave",
                            ZipCode = 53186
                        },
                        new
                        {
                            AddressID = 9,
                            City = "kenosha",
                            State = "wi",
                            StreetName = "1105 57th st",
                            ZipCode = 53140
                        });
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.Donor", b =>
                {
                    b.Property<int>("DonorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DonorId");

                    b.HasIndex("AddressId");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            DonorId = 1,
                            AddressId = 1,
                            FirstName = "jerry",
                            IsActive = true,
                            LastName = "griswold"
                        },
                        new
                        {
                            DonorId = 2,
                            AddressId = 1,
                            FirstName = "mary",
                            IsActive = true,
                            LastName = "griswold"
                        },
                        new
                        {
                            DonorId = 3,
                            AddressId = 2,
                            FirstName = "lisa",
                            IsActive = true,
                            LastName = "anderhal"
                        },
                        new
                        {
                            DonorId = 4,
                            AddressId = 3,
                            FirstName = "lucas",
                            IsActive = true,
                            LastName = "allen"
                        },
                        new
                        {
                            DonorId = 5,
                            AddressId = 4,
                            FirstName = "marissa",
                            IsActive = true,
                            LastName = "gabel"
                        },
                        new
                        {
                            DonorId = 6,
                            AddressId = 5,
                            FirstName = "jessica",
                            IsActive = true,
                            LastName = "sievers"
                        },
                        new
                        {
                            DonorId = 7,
                            AddressId = 6,
                            FirstName = "trevor",
                            IsActive = true,
                            LastName = "smith"
                        },
                        new
                        {
                            DonorId = 8,
                            AddressId = 7,
                            FirstName = "lucy",
                            IsActive = true,
                            LastName = "olson"
                        },
                        new
                        {
                            DonorId = 9,
                            AddressId = 8,
                            FirstName = "gabe",
                            IsActive = true,
                            LastName = "neuman"
                        },
                        new
                        {
                            DonorId = 10,
                            AddressId = 9,
                            FirstName = "phil",
                            IsActive = true,
                            LastName = "jefferson"
                        });
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.MedicalHistory", b =>
                {
                    b.Property<int>("MedicalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DonorId")
                        .HasColumnType("int");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasAllergies")
                        .HasColumnType("bit");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsMale")
                        .HasColumnType("bit");

                    b.Property<bool>("OnMedications")
                        .HasColumnType("bit");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("MedicalId");

                    b.HasIndex("DonorId");

                    b.ToTable("MedicalHistories");

                    b.HasData(
                        new
                        {
                            MedicalId = 1,
                            Age = 56,
                            BloodType = "a+",
                            DonorId = 1,
                            Ethnicity = "white",
                            HasAllergies = false,
                            Height = 66,
                            IsMale = true,
                            OnMedications = false,
                            Weight = 205
                        },
                        new
                        {
                            MedicalId = 2,
                            Age = 53,
                            BloodType = "b-",
                            DonorId = 2,
                            Ethnicity = "white",
                            HasAllergies = false,
                            Height = 50,
                            IsMale = false,
                            OnMedications = true,
                            Weight = 140
                        },
                        new
                        {
                            MedicalId = 3,
                            Age = 24,
                            BloodType = "b+",
                            DonorId = 3,
                            Ethnicity = "african american",
                            HasAllergies = true,
                            Height = 59,
                            IsMale = false,
                            OnMedications = false,
                            Weight = 180
                        },
                        new
                        {
                            MedicalId = 4,
                            Age = 33,
                            BloodType = "o+",
                            DonorId = 4,
                            Ethnicity = "white",
                            HasAllergies = true,
                            Height = 48,
                            IsMale = true,
                            OnMedications = true,
                            Weight = 345
                        },
                        new
                        {
                            MedicalId = 5,
                            Age = 75,
                            BloodType = "o-",
                            DonorId = 5,
                            Ethnicity = " native american/alaskan native",
                            HasAllergies = false,
                            Height = 53,
                            IsMale = false,
                            OnMedications = false,
                            Weight = 118
                        },
                        new
                        {
                            MedicalId = 6,
                            Age = 64,
                            BloodType = "ab+",
                            DonorId = 6,
                            Ethnicity = "pacific islander",
                            HasAllergies = true,
                            Height = 63,
                            IsMale = false,
                            OnMedications = false,
                            Weight = 137
                        },
                        new
                        {
                            MedicalId = 7,
                            Age = 19,
                            BloodType = "ab-",
                            DonorId = 7,
                            Ethnicity = "white",
                            HasAllergies = false,
                            Height = 56,
                            IsMale = true,
                            OnMedications = true,
                            Weight = 185
                        },
                        new
                        {
                            MedicalId = 8,
                            Age = 44,
                            BloodType = "a-",
                            DonorId = 8,
                            Ethnicity = "asian",
                            HasAllergies = true,
                            Height = 49,
                            IsMale = false,
                            OnMedications = true,
                            Weight = 285
                        },
                        new
                        {
                            MedicalId = 9,
                            Age = 22,
                            BloodType = "ab-",
                            DonorId = 9,
                            Ethnicity = "native hawaiian",
                            HasAllergies = false,
                            Height = 65,
                            IsMale = true,
                            OnMedications = false,
                            Weight = 155
                        },
                        new
                        {
                            MedicalId = 10,
                            Age = 30,
                            BloodType = "ab+",
                            DonorId = 10,
                            Ethnicity = "white",
                            HasAllergies = false,
                            Height = 55,
                            IsMale = true,
                            OnMedications = true,
                            Weight = 170
                        });
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.Donor", b =>
                {
                    b.HasOne("Capstone_Donation_API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.MedicalHistory", b =>
                {
                    b.HasOne("Capstone_Donation_API.Models.Donor", "Donor")
                        .WithMany()
                        .HasForeignKey("DonorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
