// <auto-generated />
using System;
using Capstone_Donation_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Capstone_Donation_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200310201152_RenamedStreetAddressToStreetName")]
    partial class RenamedStreetAddressToStreetName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Capstone_Donation_API.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZipCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "oconomowoc",
                            State = "wi",
                            StreetName = "329 e pleasant st",
                            ZipCode = 53066
                        },
                        new
                        {
                            Id = 2,
                            City = "milwaukee",
                            State = "wi",
                            StreetName = "324 s second st",
                            ZipCode = 53204
                        },
                        new
                        {
                            Id = 3,
                            City = "milwaukee",
                            State = "wi",
                            StreetName = "2100 n kilian pl",
                            ZipCode = 53212
                        },
                        new
                        {
                            Id = 4,
                            City = "west allis",
                            State = "wi",
                            StreetName = "1427 s 75th st",
                            ZipCode = 53214
                        },
                        new
                        {
                            Id = 5,
                            City = "naperville",
                            State = "il",
                            StreetName = "874 havenshire rd",
                            ZipCode = 60565
                        },
                        new
                        {
                            Id = 6,
                            City = "st paul",
                            State = "mn",
                            StreetName = "177 mcknight rd n",
                            ZipCode = 55119
                        },
                        new
                        {
                            Id = 7,
                            City = "kenosha",
                            State = "wi",
                            StreetName = "1105 57th st",
                            ZipCode = 53140
                        });
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.Donor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MedicalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("MedicalId");

                    b.ToTable("Donors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            FirstName = "jerry",
                            IsActive = true,
                            LastName = "griswold",
                            MedicalId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 1,
                            FirstName = "mary",
                            IsActive = true,
                            LastName = "griswold",
                            MedicalId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 2,
                            FirstName = "lisa",
                            IsActive = true,
                            LastName = "anderhal",
                            MedicalId = 3
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 3,
                            FirstName = "lucas",
                            IsActive = true,
                            LastName = "allen",
                            MedicalId = 4
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 4,
                            FirstName = "marissa",
                            IsActive = true,
                            LastName = "gabel",
                            MedicalId = 5
                        },
                        new
                        {
                            Id = 6,
                            FirstName = "jessica",
                            IsActive = true,
                            LastName = "sievers",
                            MedicalId = 6
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 5,
                            FirstName = "trevor",
                            IsActive = true,
                            LastName = "smith",
                            MedicalId = 7
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 6,
                            FirstName = "lucy",
                            IsActive = true,
                            LastName = "olson",
                            MedicalId = 8
                        },
                        new
                        {
                            Id = 9,
                            FirstName = "gabe",
                            IsActive = true,
                            LastName = "neuman"
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 7,
                            FirstName = "phil",
                            IsActive = true,
                            LastName = "jefferson"
                        });
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.MedicalHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BloodType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ethnicity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("HasAllergies")
                        .HasColumnType("bit");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<bool?>("IsMale")
                        .HasColumnType("bit");

                    b.Property<bool?>("OnMedications")
                        .HasColumnType("bit");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MedicalHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 56,
                            BloodType = "a+",
                            Ethnicity = "white",
                            HasAllergies = false,
                            Height = 66,
                            IsMale = true,
                            OnMedications = false,
                            Weight = 205
                        },
                        new
                        {
                            Id = 2,
                            Age = 53,
                            BloodType = "b-",
                            Ethnicity = "white",
                            HasAllergies = false,
                            Height = 50,
                            IsMale = false,
                            OnMedications = true,
                            Weight = 140
                        },
                        new
                        {
                            Id = 3,
                            Age = 24,
                            BloodType = "b+",
                            Ethnicity = "african american",
                            HasAllergies = true,
                            Height = 59,
                            IsMale = false,
                            OnMedications = false,
                            Weight = 180
                        },
                        new
                        {
                            Id = 4,
                            Age = 33,
                            BloodType = "o+",
                            Ethnicity = "white",
                            HasAllergies = true,
                            Height = 48,
                            IsMale = true,
                            OnMedications = true,
                            Weight = 345
                        },
                        new
                        {
                            Id = 5,
                            Age = 75,
                            BloodType = "o-",
                            Ethnicity = " native american/alaskan native",
                            HasAllergies = false,
                            Height = 53,
                            IsMale = false,
                            OnMedications = false,
                            Weight = 118
                        },
                        new
                        {
                            Id = 6,
                            Age = 64,
                            BloodType = "ab+",
                            Ethnicity = "pacific islander",
                            HasAllergies = true,
                            Height = 63,
                            IsMale = false,
                            OnMedications = false,
                            Weight = 137
                        },
                        new
                        {
                            Id = 7,
                            Age = 19,
                            BloodType = "ab-",
                            Ethnicity = "native hawaiian",
                            HasAllergies = false,
                            Height = 56,
                            IsMale = true,
                            OnMedications = true,
                            Weight = 185
                        },
                        new
                        {
                            Id = 8,
                            Age = 44,
                            BloodType = "a-",
                            Ethnicity = "asian",
                            HasAllergies = true,
                            Height = 49,
                            IsMale = false,
                            OnMedications = true,
                            Weight = 285
                        });
                });

            modelBuilder.Entity("Capstone_Donation_API.Models.Donor", b =>
                {
                    b.HasOne("Capstone_Donation_API.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Capstone_Donation_API.Models.MedicalHistory", "MedicalHistory")
                        .WithMany()
                        .HasForeignKey("MedicalId");
                });
#pragma warning restore 612, 618
        }
    }
}
